version: "3.7"

services:
   rabbit-mq:
      image: rabbitmq:3.8.16-management-alpine
      environment:
         - RABBITMQ_DEFAULT_USER=guest
         - RABBITMQ_DEFAULT_PASS=guest
      ports:
         - 5672:5672
         - 15672:15672
      restart: unless-stopped
   node:
      image: salvatorecordiano/at-node:20210527161234
      env_file: 
         - node.env
      network_mode: service:rabbit-mq
      command: sleep infinity
      volumes:
         - ../project:/project
